name: Publish
on:
  push:
    tags: ["v*"]
permissions:
  contents: read
jobs:
  verify:
    if: github.repository == 'fischerscode/legal.dart'
    uses: ./.github/workflows/verify.yml
    with:
      release-tag: ${{ github.ref_name }}
  publish:
    needs: verify
    if: github.repository == 'fischerscode/legal.dart'
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
